version: 1.1.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- Any CPU
- x86
- x64

before_build:
  - nuget restore

build:
  project: microDI.sln
  parallel: true
  verbosity: normal