version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
os: Visual Studio 2015
configuration: Release
platform: Any CPU

before_build:
  - nuget restore

build:
  project: microDI.sln
  verbosity: detailed